class_name CardTooltip
extends RefCounted

# THE shared rich card hover panel: an enlarged CardUI preview beside a detail column (name,
# generated-token note, description, attached charms). CardUI._make_custom_tooltip returns this
# in-game, and any other screen (the Forge, collection, decks…) can call build() to get the exact
# same hover, so card info reads identically everywhere. Pure read of the CardInstance — every call
# builds fresh nodes, so the returned Control is owned by whoever shows it.

const PREVIEW_SIZE := Vector2(260, 340)   # size of the enlarged card rendered inside the tooltip


static func build(inst: CardInstance, show_cost := true) -> Control:
	if inst == null:
		return null

	var panel := PanelContainer.new()
	var style  := StyleBoxFlat.new()
	style.bg_color = Color(0.08, 0.08, 0.14, 0.97)
	style.set_border_width_all(1)
	style.border_color = Color(0.45, 0.45, 0.6)
	style.set_corner_radius_all(6)
	style.set_content_margin_all(12)
	panel.add_theme_stylebox_override("panel", style)

	var hbox := HBoxContainer.new()
	hbox.add_theme_constant_override("separation", 14)
	panel.add_child(hbox)

	# Enlarged visual of the card itself (art + frame + badges). SHRINK_CENTER (not the default FILL)
	# keeps the card at PREVIEW_SIZE instead of stretching vertically when the detail column is
	# taller, which would blow up the COVERED art far past its window.
	var preview := CardUI.create(inst, show_cost)
	preview.custom_minimum_size = PREVIEW_SIZE
	preview.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	preview.mouse_filter = Control.MOUSE_FILTER_IGNORE
	hbox.add_child(preview)

	var vbox := VBoxContainer.new()
	vbox.custom_minimum_size.x = 240.0
	vbox.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	vbox.add_theme_constant_override("separation", 6)
	hbox.add_child(vbox)

	var name_lbl := Label.new()
	name_lbl.text = inst.data.display_name
	name_lbl.add_theme_font_size_override("font_size", 22)
	vbox.add_child(name_lbl)

	vbox.add_child(HSeparator.new())

	# Generated tokens explain their hidden cost: playing one taps the rook.
	if inst.source_building != null:
		var note := Label.new()
		note.text = "⚒ Generated by %s — playing it spends that Rook's attack this turn." \
			% inst.source_building.data.display_name
		note.autowrap_mode = TextServer.AUTOWRAP_WORD
		note.add_theme_font_size_override("font_size", 15)
		note.add_theme_color_override("font_color", Color(0.45, 0.95, 1.0))
		vbox.add_child(note)

	var desc := inst.data.description
	if not desc.is_empty():
		var desc_lbl := Label.new()
		desc_lbl.text          = desc
		desc_lbl.autowrap_mode = TextServer.AUTOWRAP_WORD
		desc_lbl.add_theme_font_size_override("font_size", 18)
		desc_lbl.modulate = Color(0.82, 0.82, 0.9)
		vbox.add_child(desc_lbl)

	# Charm detail: one line per attached charm, colour-matched to its on-card pip.
	if not inst.charms.is_empty():
		vbox.add_child(HSeparator.new())
		var charms_title := Label.new()
		charms_title.text = "Charms"
		charms_title.add_theme_font_size_override("font_size", 16)
		charms_title.modulate = Color(0.7, 0.7, 0.8)
		vbox.add_child(charms_title)
		for charm_id: String in inst.charms:
			var charm := CharmData.get_charm(charm_id)
			if charm == null:
				continue
			var ch_lbl := Label.new()
			ch_lbl.text = "%s  %s — %s" % [charm.letter, charm.display_name, charm.description]
			ch_lbl.autowrap_mode = TextServer.AUTOWRAP_WORD
			ch_lbl.add_theme_font_size_override("font_size", 15)
			ch_lbl.add_theme_color_override("font_color", charm.color.lightened(0.35))
			vbox.add_child(ch_lbl)

	# Active statuses: one line each (glyph, name, count, description), colour-matched to its pip.
	if not inst.statuses.is_empty():
		vbox.add_child(HSeparator.new())
		var status_title := Label.new()
		status_title.text = "Statuses"
		status_title.add_theme_font_size_override("font_size", 16)
		status_title.modulate = Color(0.7, 0.7, 0.8)
		vbox.add_child(status_title)
		for si: StatusInstance in inst.statuses:
			var sd: StatusData = si.data
			var cnt := si.count()
			var row := HBoxContainer.new()
			row.add_theme_constant_override("separation", 6)
			var icon := sd.icon_rect(22.0)
			if icon != null:
				row.add_child(icon)
			var line := "%s%s" % [sd.display_name, (" %d" % cnt) if cnt > 0 else ""]
			if not sd.description.is_empty():
				line += " — %s" % sd.description
			var st_lbl := Label.new()
			st_lbl.text = line
			st_lbl.autowrap_mode = TextServer.AUTOWRAP_WORD
			st_lbl.size_flags_horizontal = Control.SIZE_EXPAND_FILL
			st_lbl.add_theme_font_size_override("font_size", 15)
			st_lbl.add_theme_color_override("font_color", sd.color.lightened(0.35))
			row.add_child(st_lbl)
			vbox.add_child(row)

	return panel
