class_name CardTooltip
extends RefCounted

# THE shared rich card hover panel: an enlarged CardUI preview beside a detail column (name,
# generated-token note, description, abilities, attached charms). CardUI._make_custom_tooltip
# returns this in-game, and any other screen (the Forge, collection, decks…) can call build() to
# get the exact same hover, so card info reads identically everywhere. Pure read of the
# CardInstance — every call builds fresh nodes, so the returned Control is owned by whoever
# shows it.
#
# SIZING RULE: every autowrap label gets custom_minimum_size.x pinned to its actual column
# width. Without it, Godot computes an autowrap label's minimum HEIGHT as if the label were
# squeezed to its narrowest possible width (roughly the longest word), so nested containers
# reserve room for a dozen phantom lines and the tooltip balloons with empty space far past
# its real content ("tooltip_large" bug). Pinned width ⇒ min height == rendered height ⇒ the
# panel is exactly as big as its content.

const PREVIEW_SIZE := Vector2(260, 340)   # size of the enlarged card rendered inside the tooltip
# Small ability-widget views in the detail column (260:340 aspect, same as everywhere).
const ABILITY_WIDGET_SIZE := Vector2(96, 126)
# The detail column's fixed width; all autowrap labels pin against it (see SIZING RULE).
const COLUMN_WIDTH := 240.0

# Dark panel (stands out against the light board theme) — text palette is light-on-dark.
const BG_COLOR := Color(0.09, 0.095, 0.13, 0.97)
const BORDER_COLOR := Color(0.45, 0.47, 0.6, 0.9)
const TEXT_MAIN := Color(0.93, 0.9, 0.82)     # description / ability text
const TEXT_TITLE := Color(0.97, 0.96, 0.92)   # the card name
const TEXT_SECTION := Color(0.72, 0.7, 0.62)  # "Abilities"/"Charms"/"Statuses" headers
const TEXT_NOTE := Color(0.55, 0.85, 0.95)    # the generated-token note


# `scale` sizes the whole panel up proportionally — preview, column width, fonts, pads. Fonts
# scale through their point size (not a canvas transform), so text stays crisp at any factor.
# 1.0 = the hover tooltip; CardInspector passes the factor that fills the screen (see there).
static func build(inst: CardInstance, show_cost := true, scale := 1.0) -> Control:
	if inst == null:
		return null
	var s := scale

	var panel := PanelContainer.new()
	var style  := StyleBoxFlat.new()
	style.bg_color = BG_COLOR
	style.set_border_width_all(1)
	style.border_color = BORDER_COLOR
	style.set_corner_radius_all(6)
	style.set_content_margin_all(12.0 * s)
	panel.add_theme_stylebox_override("panel", style)

	var hbox := HBoxContainer.new()
	hbox.add_theme_constant_override("separation", int(14.0 * s))
	panel.add_child(hbox)

	# Enlarged visual of the card itself (art + frame + badges). SHRINK_CENTER (not the default FILL)
	# keeps the card at PREVIEW_SIZE instead of stretching vertically when the detail column is
	# taller, which would blow up the COVERED art far past its window.
	var preview := CardUI.create(inst, show_cost)
	preview.custom_minimum_size = PREVIEW_SIZE * s
	preview.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	preview.mouse_filter = Control.MOUSE_FILTER_IGNORE
	hbox.add_child(preview)

	var col_w := COLUMN_WIDTH * s
	var vbox := VBoxContainer.new()
	vbox.custom_minimum_size.x = col_w
	vbox.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	vbox.add_theme_constant_override("separation", int(6.0 * s))
	hbox.add_child(vbox)

	var name_lbl := Label.new()
	name_lbl.text = inst.data.display_name
	name_lbl.add_theme_font_size_override("font_size", int(22.0 * s))
	name_lbl.add_theme_color_override("font_color", TEXT_TITLE)
	vbox.add_child(name_lbl)

	vbox.add_child(HSeparator.new())

	# Generated tokens explain their hidden cost: playing one taps the rook.
	if inst.source_building != null:
		var note := Label.new()
		# No leading icon glyph here — the default font (Baloo2-ExtraBold) is missing several
		# symbol glyphs (⚒, ✓, ●, the old ✕), which render broken on web/mobile builds where
		# there's no system-font fallback; see ScreenUI.CLOSE_GLYPH for the same issue.
		note.text = "Generated by %s — playing it spends that Rook's attack this turn." \
			% inst.source_building.data.display_name
		vbox.add_child(_wrap_label(note, col_w, int(15.0 * s), TEXT_NOTE))

	var desc := inst.data.description
	if not desc.is_empty():
		vbox.add_child(_rich_label(desc, col_w, int(18.0 * s), TEXT_MAIN))

	# Activated abilities: a SMALL ability-widget view per ability beside its description —
	# the same visual the tray uses, so "this is an ability" reads identically everywhere.
	# Info-only here (mouse-ignored, not draggable); activation stays in the tray.
	var abilities: Array = inst.ability_list()
	if not abilities.is_empty():
		vbox.add_child(HSeparator.new())
		vbox.add_child(_section_title("Abilities", s))
		for ab: AbilityData in abilities:
			vbox.add_child(_ability_row(inst, ab, s))

	# Charm detail: one line per attached charm, colour-matched to its on-card pip.
	if not inst.charms.is_empty():
		vbox.add_child(HSeparator.new())
		vbox.add_child(_section_title("Charms", s))
		for charm_id: String in inst.charms:
			var charm := CharmData.get_charm(charm_id)
			if charm == null:
				continue
			var ch_line := "%s  %s — %s" % [charm.letter, charm.display_name, charm.description]
			vbox.add_child(_rich_label(ch_line, col_w, int(15.0 * s), charm.color.lightened(0.35)))

	# Active statuses: one line each (glyph, name, count, description), colour-matched to its pip.
	if not inst.statuses.is_empty():
		vbox.add_child(HSeparator.new())
		vbox.add_child(_section_title("Statuses", s))
		for si: StatusInstance in inst.statuses:
			var sd: StatusData = si.data
			var cnt := si.count()
			var row := HBoxContainer.new()
			row.add_theme_constant_override("separation", int(6.0 * s))
			var icon := sd.icon_rect(22.0 * s)
			if icon != null:
				row.add_child(icon)
			var line := "%s%s" % [sd.display_name, (" %d" % cnt) if cnt > 0 else ""]
			if not sd.description.is_empty():
				line += " — %s" % sd.description
			# The pip + the row's separation, so pip + text fill the column.
			row.add_child(_rich_label(line, col_w - 28.0 * s, int(15.0 * s),
				sd.color.lightened(0.35)))
			vbox.add_child(row)

	return panel


# One ability line: the small widget (built exactly like the tray's tokens, so armed autocast
# brackets/effects read here too) beside the ability's name and description.
static func _ability_row(inst: CardInstance, ab: AbilityData, s := 1.0) -> Control:
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", int(10.0 * s))

	var tok := CardInstance.from_data(ab.display_card())
	tok.owner = inst.owner
	tok.row = -1
	tok.col = -1
	tok.source_building = inst
	tok.ability = ab
	var w := AbilityWidget.create_for(tok)
	w.custom_minimum_size = ABILITY_WIDGET_SIZE * s
	w.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	w.mouse_filter = Control.MOUSE_FILTER_IGNORE
	w.draggable = false
	row.add_child(w)

	var line := ab.display_name
	if not ab.description.is_empty():
		line += " — " + ab.description
	# Widget width + the row's separation leaves this much column for the text.
	var lbl := _rich_label(line, (COLUMN_WIDTH - ABILITY_WIDGET_SIZE.x - 10.0) * s,
		int(15.0 * s), TEXT_MAIN)
	lbl.size_flags_vertical = Control.SIZE_SHRINK_CENTER
	row.add_child(lbl)
	return row


static func _section_title(text: String, s := 1.0) -> Label:
	var lbl := Label.new()
	lbl.text = text
	lbl.add_theme_font_size_override("font_size", int(16.0 * s))
	lbl.add_theme_color_override("font_color", TEXT_SECTION)
	return lbl


# Styles a label as wrapped detail text with its width PINNED (see the SIZING RULE up top —
# unpinned autowrap labels report phantom min heights and balloon the panel).
static func _wrap_label(lbl: Label, width: float, font_size: int, color: Color) -> Label:
	lbl.autowrap_mode = TextServer.AUTOWRAP_WORD
	lbl.custom_minimum_size.x = width
	lbl.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	lbl.add_theme_font_size_override("font_size", font_size)
	lbl.add_theme_color_override("font_color", color)
	return lbl


# Rules-text counterpart of _wrap_label: a RichTextLabel so element/piece keywords render as
# inline icons (TextIcons). Same SIZING RULE — width pinned so fit_content reports the real
# rendered height instead of phantom lines.
static func _rich_label(text: String, width: float, font_size: int, color: Color) -> RichTextLabel:
	var rtl := TextIcons.rich_label(text, font_size, color)
	rtl.custom_minimum_size.x = width
	rtl.size_flags_horizontal = Control.SIZE_EXPAND_FILL
	return rtl
