@tool
extends Button
class_name GlossyButton
# Nine-patch "Bold & Punchy" button (see D:\Godot\ArtDirection\Card game UI system\
# design_handoff_glossy_buttons — Option A, the design's recommended/verified approach, replacing
# the earlier hand-translated procedural shader that kept drifting from the reference across many
# rounds). All the button's actual geometry (shoulder, socket, riser, candy split, sheen, rim
# line, corner glint, gradient outline) is baked once into a grayscale texture
# (button_shademap_*.png); a tiny recolor shader (button_recolor.gdshader) tints it by
# `base_color` at runtime. Godot's native NinePatchRect stretch keeps the baked corners/riser
# crisp at any button size — only the flat middle bands stretch.
#
# Adapted for this project rather than copied wholesale:
# - Kept CHUNKY_FONT + the disabled/toggle_mode handling the handoff doesn't cover (see _process).
# - Three baked texture sizes (small/medium/large — see _TIERS), not the handoff's single 600×324
#   asset. Nine-patch margins are fixed TEXTURE pixels that don't shrink with the node; the
#   original asset's margins (~58px sides, ~54px bottom) don't fit this project's smallest
#   buttons (52-88px tall footer/header buttons — smaller than the margins alone). Generated by
#   downscaling the source texture (proportionally shrinks the baked margins with it) rather than
#   waiting on hand-baked variants; ping the designer for real baked assets at the specific sizes
#   this undershoots if the softness from downscaling ever becomes visible.
# - `ink` is kept as an export purely for call-site compatibility (every button sets it via
#   ScreenUI.action_button) but is now a NO-OP — the recolor shader has no separate ink uniform;
#   the outline color is implicit in how dark the shademap's own darkest pixels are.
# - No baked pressed/hover state exists in the shademap (it's a single static "up" texture), so
#   pressed/toggle feedback is faked with a modulate darken + a small downward shift instead.
# - The Forge FAB (map.gd) needed an exact circle, which a nine-patch corner can't produce — it
#   no longer uses GlossyButton at all; see map.gd for its own plain-Button styling.

const CHUNKY_FONT := preload("res://assets/fontd/Baloo_2/static/Baloo2-ExtraBold.ttf")

const _TEX_SMALL := preload("res://assets/ui/button_shademap_small.png")
const _TEX_MEDIUM := preload("res://assets/ui/button_shademap_medium.png")
const _TEX_LARGE := preload("res://assets/ui/button_shademap_large.png")

# Picked by the button's own min(width, height) — see _pick_tier. Margins pixel-measured off the
# source 600×324 asset (~58px corner/side, ~54px bottom incl. the riser band), scaled down with
# the texture itself for "small"/"medium".
const _TIERS := [
	{"max_side": 110.0, "texture": _TEX_SMALL, "margin_sides": 17, "margin_bottom": 16},
	{"max_side": 220.0, "texture": _TEX_MEDIUM, "margin_sides": 32, "margin_bottom": 30},
	{"max_side": INF, "texture": _TEX_LARGE, "margin_sides": 58, "margin_bottom": 54},
]

@export var base_color: Color = Color("f6871d"):
	set(v): base_color = v; _apply()
@export var ink: Color = Color("1c2136")   # unused — see class comment; kept for call-site compat

var _skin: NinePatchRect
var _tier_index: int = -1
var _was_disabled := false   # see _process — Button has no signal for `disabled` changing
var _was_toggled := false    # see _process — persistent toggle_mode state (e.g. active tabs)


func _ready() -> void:
	_build()
	if not resized.is_connected(_on_resized):
		resized.connect(_on_resized)
	if not button_down.is_connected(_on_down):
		button_down.connect(_on_down)
		button_up.connect(_on_up)
	_apply()
	call_deferred("_apply")   # size is not final until after layout
	_was_disabled = disabled
	_apply_disabled()
	_was_toggled = button_pressed
	_apply_toggle()


func _process(_delta: float) -> void:
	if disabled != _was_disabled:
		_was_disabled = disabled
		_apply_disabled()
	if toggle_mode and button_pressed != _was_toggled:
		_was_toggled = button_pressed
		_apply_toggle()


func _apply_disabled() -> void:
	modulate = Color(1, 1, 1, 0.5) if disabled else Color.WHITE


# No baked pressed texture exists, so "pushed in" is faked: darken + nudge down a couple px.
# button_down/button_up below drive the same look for an ordinary momentary click.
func _apply_toggle() -> void:
	_set_pressed_look(button_pressed)


func _set_pressed_look(is_pressed: bool) -> void:
	if _skin == null:
		return
	_skin.modulate = Color(0.82, 0.82, 0.82) if is_pressed else Color.WHITE
	_skin.position.y = 3.0 if is_pressed else 0.0


func _build() -> void:
	for s in ["normal", "hover", "pressed", "focus", "disabled"]:
		add_theme_stylebox_override(s, StyleBoxEmpty.new())
	add_theme_font_override("font", CHUNKY_FONT)
	if _skin == null:
		_skin = NinePatchRect.new()
		_skin.name = "Skin"
		_skin.show_behind_parent = true
		_skin.mouse_filter = Control.MOUSE_FILTER_IGNORE
		_skin.set_anchors_preset(Control.PRESET_FULL_RECT)
		_skin.axis_stretch_horizontal = NinePatchRect.AXIS_STRETCH_MODE_STRETCH
		_skin.axis_stretch_vertical = NinePatchRect.AXIS_STRETCH_MODE_STRETCH
		var mat := ShaderMaterial.new()
		mat.shader = load("res://assets/ui/shaders/button_recolor.gdshader")
		_skin.material = mat
		add_child(_skin)
		move_child(_skin, 0)


func _pick_tier(min_side: float) -> int:
	for i in _TIERS.size():
		if min_side <= _TIERS[i].max_side:
			return i
	return _TIERS.size() - 1


func _apply() -> void:
	if _skin == null:
		return
	var min_side := minf(size.x, size.y)
	if min_side > 1.0:
		var tier := _pick_tier(min_side)
		if tier != _tier_index:
			_tier_index = tier
			var t: Dictionary = _TIERS[tier]
			_skin.texture = t.texture
			_skin.patch_margin_left = t.margin_sides
			_skin.patch_margin_right = t.margin_sides
			_skin.patch_margin_top = t.margin_sides
			_skin.patch_margin_bottom = t.margin_bottom
	var mat: ShaderMaterial = _skin.material
	mat.set_shader_parameter("base_color", base_color)
	var o := base_color.darkened(0.55)
	add_theme_color_override("font_color", Color.WHITE)
	add_theme_color_override("font_outline_color", o)
	add_theme_constant_override("outline_size", 8)
	add_theme_color_override("font_shadow_color", o)
	add_theme_constant_override("shadow_offset_x", 0)
	add_theme_constant_override("shadow_offset_y", 3)


func _on_resized() -> void:
	_apply()


func _on_down() -> void:
	_set_pressed_look(true)


func _on_up() -> void:
	_set_pressed_look(toggle_mode and button_pressed)
